import type { Metadata } from 'next'
import './globals.css';
import { ThemeProvider } from './utils/theme-provider';
import 'react-toastify/dist/ReactToastify.css';
import { NextAuthProvider } from '@/pages/api/auth/NextAuthProvider';

import { ReduxProvider } from '@/redux/ReduxProvider'; 
import Header from './components/Header';
import { Custom } from './utils/loader';

export const metadata: Metadata = {
  title: '𝙚𝘿𝙚𝙢𝙮-𝐎𝐧𝐥𝐢𝐧𝐞 𝐂𝐨𝐮𝐫𝐬𝐞𝐬',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`bg-white duration-300 bg-no-repeat dark:bg-dark`}>
          <NextAuthProvider>
            <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
              <Custom>
                {children}
              </Custom>
            </ThemeProvider>
          </NextAuthProvider>
        </body>
      </ReduxProvider>
    </html>
  )
}